In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [44]:
df = pd.DataFrame({'Nome': ['Joao da silva ', 'Pedro fernandes' , 'Maria freitas','Paula gonçalves','ana freitas','luiz costa','andre souza','patricia silva', 'regina lima','alfredo souza','margarete cunha','pedro barbosa','ricardo alves','marcio rezende','ana carolina chaves'],
                   'Idade': [36,51,26,25,29,53,42,38,35,45,26,37,24,31,29],
                 'Salario': [6300,5700,4500,3800,3200,7300,7100,5600,6400,7000,3700,6500,4000,5100,4500]}
                 )
df

Nome  Idade  Salario
0        Joao da silva      36     6300
1       Pedro fernandes     51     5700
2         Maria freitas     26     4500
3       Paula gonçalves     25     3800
4           ana freitas     29     3200
5            luiz costa     53     7300
6           andre souza     42     7100
7        patricia silva     38     5600
8           regina lima     35     6400
9         alfredo souza     45     7000
10      margarete cunha     26     3700
11        pedro barbosa     37     6500
12        ricardo alves     24     4000
13       marcio rezende     31     5100
14  ana carolina chaves     29     4500

Fiz todas as duas como explicado em aula e notebook! ps: usei sua função para montar a tabela bem feitinha.

Resposta 1:

In [14]:
df["Idade"].unique()

array([36, 51, 26, 25, 29, 53, 42, 38, 35, 45, 37, 24, 31], dtype=int64)

In [15]:
df["Idade"].value_counts()

26    2
29    2
35    1
36    1
37    1
38    1
42    1
45    1
51    1
53    1
24    1
25    1
31    1
Name: Idade, dtype: int64

In [23]:
dados = df['Idade']

In [49]:
hist, bin_edges = np.histogram(dados, bins='auto')

In [29]:
hist

array([6, 2, 3, 2, 2], dtype=int64)

In [30]:
bin_edges

array([24. , 29.8, 35.6, 41.4, 47.2, 53. ])

In [31]:
h = np.diff(bin_edges)
h[0]

5.800000000000001

In [32]:
fi, classes = np.histogram(dados,bins=5)
fi

array([6, 2, 3, 2, 2], dtype=int64)

In [33]:
fr = fi/fi.sum()
fr

array([0.4       , 0.13333333, 0.2       , 0.13333333, 0.13333333])

In [35]:
frnorm = fi/(fi.sum() * np.diff(classes))
frnorm

array([0.06896552, 0.02298851, 0.03448276, 0.02298851, 0.02298851])

In [39]:
F = fi.cumsum()
F

array([ 6,  8, 11, 13, 15], dtype=int64)

In [47]:
def dist_frequencia_classes(x, nc='auto'):
    fa,classes= np.histogram(x, bins=nc) 
    fa = fa.astype(int)
    fr = np.around(fa/fa.sum()*100,decimals=2) 
    fc = np.cumsum(fa).astype(int) 
  
    classe_str = []
    for i in range(len(classes)):
        if i<=len(classes)-2:
            classe_str.append('{:2.2f} |-- {:2.2f}' .format(classes[i],classes[i+1]))
        else:
            break        
   
    return pd.DataFrame({'Idade':classe_str, 
                         'fi': fa,
                         'fr': fr,
                         'Fc': fc
                        }).set_index('Idade') 


In [48]:
dist_frequencia_classes(dados, nc=5)

fi     fr  Fc
Idade                         
24.00 |-- 29.80   6  40.00   6
29.80 |-- 35.60   2  13.33   8
35.60 |-- 41.40   3  20.00  11
41.40 |-- 47.20   2  13.33  13
47.20 |-- 53.00   2  13.33  15

Resposta 2

In [50]:
dados = df['Salario']

In [51]:
hist, bin_edges = np.histogram(dados)

In [52]:
hist

array([1, 3, 0, 2, 1, 1, 1, 2, 1, 3], dtype=int64)

In [53]:
bin_edges

array([3200., 3610., 4020., 4430., 4840., 5250., 5660., 6070., 6480.,
       6890., 7300.])

In [54]:
h = np.diff(bin_edges)
h[0]

410.0

In [55]:
fi, classes = np.histogram(dados,bins=5)
fi

array([4, 2, 2, 3, 4], dtype=int64)

In [56]:
fr = fi/fi.sum()
fr

array([0.26666667, 0.13333333, 0.13333333, 0.2       , 0.26666667])

In [57]:
frnorm = fi/(fi.sum() * np.diff(classes))
frnorm

array([0.0003252, 0.0001626, 0.0001626, 0.0002439, 0.0003252])

In [58]:
frnorm*np.diff(classes)

array([0.26666667, 0.13333333, 0.13333333, 0.2       , 0.26666667])

In [59]:
F = fi.cumsum()
F

array([ 4,  6,  8, 11, 15], dtype=int64)

In [62]:
def dist_frequencia_classes(x, nc='auto'):
    
    fa,classes= np.histogram(x, bins=nc) 
    fa = fa.astype(int)
    
    fr = np.around(fa/fa.sum()*100,decimals=2) 
    fc = np.cumsum(fa).astype(int)  
    classe_str = []
    for i in range(len(classes)):
        if i<=len(classes)-2:
            classe_str.append('{:2.2f} |-- {:2.2f}' .format(classes[i],classes[i+1]))
        else:
            break        
    return pd.DataFrame({'Salario':classe_str, 
                         'fi': fa,
                         'fr': fr,
                         'Fc': fc
                        }).set_index('Salario') 

In [63]:
dist_frequencia_classes(dados, nc=5)

fi     fr  Fc
Salario                           
3200.00 |-- 4020.00   4  26.67   4
4020.00 |-- 4840.00   2  13.33   6
4840.00 |-- 5660.00   2  13.33   8
5660.00 |-- 6480.00   3  20.00  11
6480.00 |-- 7300.00   4  26.67  15