# Respostas

    Questão 1: Como importar a biblioteca numpy e verificar a versão utilizada?

A biblioteca numpy é importada da seguinte maneira e ainda sua versão é :

In [3]:
import numpy as np #faz a importação
import numpy ; numpy.version.version #verifica a versão


'1.20.1'

    Questão 2: Explique, com suas palavras o conceito de vetorização e broadcasting que numpy implementa.

Vetorização é utilizada para aplicar uma função a uma array inteira, ao contrario do que map faz. Broadcasting permite a aplicação aritmetica sobre circustancias diferentes, exemplo: (4,4) e (1,4) 

    Questão 3: Liste as diferenças entre uma lista, um dicionario, um array numpy, dando exemplos de aplicação de em cada tipo seria mais interessante.

Diferenças:
- Lista, Caso voce precise de uma coisa ordenada e indexada por posição, pode haver elementos de tipo diferente, coisa que o array não faz, recomenda-se a utilização em casos pequenos, que nao use muito dados e tenha que ser utilizado diversos tipos de dados
- Dicionario, Não é obrigado a ser ordenado e o acesso aos itens e é feito por chaves, é utilizado em diversos banco de dados.
- Array Numpy, Tem o mesmo tipo de dados, é mais leve em termos de memoria, da para fazer a operações em todos os items de forma que nao será feito um por um, Utilizado em grandes conjuntos de dados, complexos, pois será feito com agilidade e eficiencia.

    Questão 4: Forme a matriz: [[1, 6, 11], [2, 7, 12], [3, 8, 13], [4, 9, 14], [5, 10, 15]] usando lista e array Numpy.

In [39]:
#usando lista
m = []
f = 0
z = 0
print("Matriz Lista:")
for i in range(5):
    lin = []
    f += 1 
    z = f
    lin.append(f)
    for j in range(2):
        z += 5
        lin.append(z)
    print(lin)

#usando array
import numpy as np 
print('Matriz Array:')
m = np.arange(1,16)
m.reshape((5,3), order = "F")

Matriz Lista:
[1, 6, 11]
[2, 7, 12]
[3, 8, 13]
[4, 9, 14]
[5, 10, 15]
Matriz Array:


array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

    Questão 5:Usando numpy, crie: 
    (a) um vetor de 10 elementos entre 1 e 20:

    (b) um vetor entre 1 e 20, com passo de 2:

    (c) uma matriz 3x3 cujos elementos da diagonal sejam o vetor [1,2,3] e os demais sejam todos 0:

In [20]:
#A
np.random.randint(1, 20, 10)

array([14,  6, 18, 14,  8,  6, 12, 13,  6,  3])

In [16]:
#B
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [17]:
#C
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])